server:
  port: 80
spring:
  application:
    name: course_notifications
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/subscript?serverVersion=8.0
    username: my-user
    password: +X%j5AW47
logging:
  file:
    path: logs/
    name: application.log
